server:
  port: 8003

spring:
    cloud:
        config:
            allowOverride: false
            failFast: true
            overrideNone: false
            overrideSystemProperties: false


foo: i am foo,but i changed!
